version: '4'
services:
  web:
    container_name: digital_experts_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - /app/node_modules
      - .:/app
